table bad_flat_order_items
	lineageTag: 12c0559f-b1d4-4d52-bb08-5d96f288cbfa

	measure Revenue = SUM(bad_flat_order_items[price])
		formatString: #,0.00
		lineageTag: add406ce-3444-4e03-b108-7141e74c3056

	measure 'Order Count' = DISTINCTCOUNT(bad_flat_order_items[order_id])
		formatString: #,0
		lineageTag: 2137650b-a85d-4159-b2ae-ec78fd6a63e1

	measure 'Bad Filter (measure)' = CALCULATE([Revenue], FILTER(bad_flat_order_items, [Revenue] > 100))
		formatString: #,0.00
		lineageTag: a91b0c4d-448d-4b48-a58f-4cbaccf79dd4

	column order_id
		dataType: string
		lineageTag: 1948ac40-5101-4b29-bf2a-3259d36e6451
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: 4f6af45b-9bb4-4a47-874b-5dc53a33a8e6
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 753cf6ca-c0b7-445e-9b8f-c3613edb252e
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: b8147166-84e7-4d11-872a-3e7a3afa0110
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: string
		lineageTag: 8083d997-87af-42cc-8fe8-e5420f876a42
		summarizeBy: none
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column shipping_limit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f8ac5830-af46-442a-aefb-e72cec5ccab0
		summarizeBy: none
		sourceColumn: shipping_limit_date

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: #,0.00
		lineageTag: 84328378-146b-41c6-ab31-0ae0f6db6f9b
		summarizeBy: none
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column freight_value
		dataType: decimal
		formatString: #,0.00
		lineageTag: d28a7965-bd67-4648-8200-237da32d79cf
		summarizeBy: none
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: e474a0ef-eadd-4016-b023-7f28f795104d
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: be4d702e-fcab-4aaf-b906-44b3a70c6f84
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: fd0ba208-f23e-49de-a59c-4c8067bd5fef
		summarizeBy: none
		sourceColumn: order_approved_at

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 27e38b38-b76d-4735-ab2a-a132fb6ce008
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: cd7eb7cd-0167-48af-b8de-487623eaf6bd
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 598f602c-cf23-48f5-8a96-cebcc13efb3c
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 91f6b085-fb10-4239-b4dc-814ec5329293
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: string
		lineageTag: 457c21d6-4b29-4ea1-babf-46e69300d0ad
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 561cdbb4-332d-418f-8ba0-a063133b126e
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 3619d163-efdb-41ea-ba6c-28d7fd59758a
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: 63ea5098-bd90-4f03-8deb-630f3cc60301
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_name_lenght
		dataType: string
		lineageTag: 281419c7-0294-406d-a5de-b8acd887cc4e
		summarizeBy: none
		sourceColumn: product_name_lenght

		annotation SummarizationSetBy = Automatic

	column product_description_lenght
		dataType: string
		lineageTag: 045b3d6a-dc54-4147-a85f-2302dbf72ef6
		summarizeBy: none
		sourceColumn: product_description_lenght

		annotation SummarizationSetBy = Automatic

	column product_photos_qty
		dataType: string
		lineageTag: 96ec8214-624d-401e-89c2-187568d47bc5
		summarizeBy: none
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: string
		lineageTag: 9e5f7c2b-12a6-4d20-9f65-06a4fd53fe38
		summarizeBy: none
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: string
		lineageTag: 560bba03-e10c-472f-810b-f0591123246f
		summarizeBy: none
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: string
		lineageTag: 5f9b88da-5052-47df-b85f-7cb7e17e37fa
		summarizeBy: none
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: string
		lineageTag: d77e641e-0583-4680-aacf-eb7f3603393d
		summarizeBy: none
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	column seller_zip_code_prefix
		dataType: string
		lineageTag: 97544a75-43c0-4241-a420-803cc9ee6276
		summarizeBy: none
		sourceColumn: seller_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column seller_city
		dataType: string
		lineageTag: e91f2a0a-02ab-4360-a835-2cb6d07bd0b6
		summarizeBy: none
		sourceColumn: seller_city

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: 870af04e-3b0b-4ea9-ab36-f63ac3fd23db
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: string
		lineageTag: adf1dbd2-34dc-4fdc-a3fa-5b6a9674143b
		summarizeBy: none
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic


	column 'Purchase Date' = DATE(YEAR(bad_flat_order_items[order_purchase_timestamp]), MONTH(bad_flat_order_items[order_purchase_timestamp]), DAY(bad_flat_order_items[order_purchase_timestamp]))
		dataType: dateTime
		formatString: General Date
		lineageTag: bd4818b2-895e-4b72-aac9-84aa42bcd472
		summarizeBy: none

	partition bad_flat_order_items = m
		mode: import
		source =
				let
				    Source  = Sql.Database("<sql-endpoint>.datawarehouse.fabric.microsoft.com", "OlistLH"),
				    Data    = Source{[Schema = "silver", Item = "bad_flat_order_items"]}[Data],
				    Slim    = Table.RemoveColumns(Data, {"review_comment_message"}),
				    NoBlank = Table.ReplaceValue(Slim, "", null, Replacer.ReplaceValue, {"shipping_limit_date", "order_purchase_timestamp", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"}),
				    Typed   = Table.TransformColumnTypes(NoBlank, {{"shipping_limit_date", type datetime}, {"order_purchase_timestamp", type datetime}, {"order_approved_at", type datetime}, {"order_delivered_carrier_date", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}, {"price", Currency.Type}, {"freight_value", Currency.Type}}, "en-US")
				in
				    Typed
